### DISCUSSION TITLE
How to automatize ip reconfiguration ?

### DISCUSSION THREAD

**Discussion by doug-last** [ksheumaker/homeassistant-apsystems_ecur#137] [Q&A] [answered]
My ecu eventually changes his ip adress and i'm unable to force an fixed ip for the ecu.

Knowing that, i need to reconfigure the homeassistant each time the ip changes, so, i want to automatize the reconfiguration of the ip.
I already track the new ip adress via hass "Arpscan Device Tracker Component" and made part of the automation.

I don't know how to change the config via command on the automation, I'm using 'notification' just to show the new ip:

(the 'device_tracker.60c5a87abc41' is my ecu found by 'arpscan' component)

```
alias: find_ecu
description: track the device ECU by mac address on network and show the ip when is found.
trigger:
  - platform: state
    entity_id:
      - device_tracker.60c5a87abc41
    from: not_home
    to: home
    for:
      hours: 0
      minutes: 0
      seconds: 30
condition:
  - condition: device
    type: is_off
    device_id: 3b5f663480f19e98145833866dc6e85a
    entity_id: switch.ecu_query_device
    domain: switch
    for:
      hours: 0
      minutes: 5
      seconds: 0
action:
  - service: notify.notify
    data:
      message: |
        "ECU is now at: "{{ state_attr('device_tracker.60c5a87abc41','ip' ) }} "
mode: single

```

**Comment by HAEdwin** [comment]
Hi Doug, why is it not possible to bind a fixed ip address to the ECU? Is you router/modem not able to do this (bind to MAC address for instance)? What kind of router do you have? It's easier to solve this at the DHCP side of the network.

**Reply by doug-last** [reply]
My router is the moden provided by my isp, the older model had the option to bind, this one don't, and randomize all ip's at each reboot.

**Reply by ViperRNMC** [reply]
what is the name/type router from your isp

**Reply by doug-last** [reply]
model: "F@st3895 Claro DOCSIS 3.1"
the firmware is custom for isp "claro"

**Reply by ViperRNMC** [reply]
Can't find any manual for this router, but it has bridge mode. Maybe better to get a other router.

**Reply by doug-last** [reply]
The best option is to buy a proper router between the isp router and my devices, but it costs money.
A non option is for isp to replace the router, is not under my control (the models are standardized and sabotaged¹/modified, and it's replaced every few years when the technology they use on the street changes.). ¹sabotaged because this router with fabric firmware have all router options, they replaced the firmware to show only the features they chose.
The free option is to add something similar to an 'auto-reconfigure on ip change', but requires effort.
PSA: I cannot demand that kind of feature, if it seems like i am in the wrong tone is the result of lack of fluency.

**Reply by HAEdwin** [reply]
What if you can disable the DHCP server on the router and use this add on? 
![image](https://user-images.githubusercontent.com/82239374/206350622-784ebcda-84f5-41ad-acef-e0fe54cc255b.png)

**Reply by doug-last** [reply]
The system runs on a house of older people, if the computer that runs HA freezes or turn off, it will stay off for a few days until i come over, and going to stay without dhcp in the meantime. 
Any additional complexity that may break something must be avoided, and any problem they have with internet must be solved with: unplug-plug, wait 5 minutes, call ISP.
I also tried running a wifi network just for the ECU with pfsense, but when the computer froze, the ECU had no internet access for that day.

**Reply by HAEdwin** [reply]
As with all things, sometimes you have to rely on hardware but I understand the challenge you're facing. Would it be easier if you add a simple router which is capable of running a DHCP server? I once used a simple TP-Link router as a DHCP server because the DHCP server in 
 the Fritzbox could not handle many changing guest nodes (still can't I believe).

**Comment by ViperRNMC** [comment]
why not setting the ip in the ECU is it is not possible in the router?
http://<ip>/index.php/management/network

<img width="615" alt="Scherm­afbeelding 2022-11-23 om 12 10 50" src="https://user-images.githubusercontent.com/18293340/203532591-f738dd81-c8f6-45e9-bff7-fca28d7d2539.png">

**Reply by doug-last** [reply]
I tried to configure the ip via management app, it works for a few seconds. (Tested with ping from pc, older (dhcp) and newer (assigned) ip, both responding)
Them it becomes unreachable via wifi on both ip. 
-powercycle:
-minutes after: still no response (100% packet loss on both ips)
-20 minutes later: return to "assign automatically"
-older dhcp ip responds again.


Psa: i don't know if its a bug on ecu or router, the router is on defaults (except wifi password), router ipv4 firewall is disabled.

**Reply by doug-last** [reply]
i tried via the index.php, got -almost- the same result.
ip became unreacheble, checked via app(since via browser is unreachable), ip and network is correct, but now i had to reconfigure wifi network and password and return ip to automatically to work

**Comment by doug-last** [comment, marked as answer]
Solution found:

Run a script to update the file /etc/hosts to assign the ECU IP to an address.

Instructions:

on config folder create the file:
update_local_dns_ecu.sh 
```
#!/bin/sh

arp-scan -gl -t 15000 -r 2 | grep -h "Beijing LT Honway" | cut -f 1 | { 
  result=$(xargs -I{} sed '/cu.local/{s/.*/{} ecu.local \#'" $(date)"' /;h};${x;/ecu.local \# $(date)/!{x;s/^/{} ecu.local \#'" $(date) "'\n/;}}' /etc/hosts)
  if [ -n "$result" ]; then
	echo "$result" | uniq
	echo "$result" | uniq  > /etc/hosts
  fi
}
```
notes: don't forget to make executable: chmod +x, it will not update every time, sometimes the ecu is not found by arp-scan, it takes around 30 seconds, it works by searching the line containing "Beijing LT Honway" on the result of arp-scan, being that the manufacturer of the wifi adapter of my ECU, other models may need a different pattern, and it will break if other device on the network are made by the same manufacturer (not tested)


to run the script every 5 minutes:

all on homeassistant config folder:
automations.yaml
```
- id: '1676072297092'
  alias: update ecu ip every 5 minutes
  description: this trigger calls the update_local_dns_ecu to update the file /etc/hosts
    with the ip of my ecu if found on the network by arpscan
  trigger:
  - platform: time_pattern
    minutes: /5
  condition: []
  action:
  - service: shell_command.update_local_dns_ecu
    data: {}
  mode: single

```
configuration.yaml  add:
```
shell_command:
  update_local_dns_ecu: ./update_local_dns_ecu.sh

```

then: reboot homeassistant
then: wait half an hour (or if you see the IP updated on '''cat /etc/hosts''')

after that: go to homeassistant and on devices, on configure ECU, instead of writing the IP of the ECU, write 'ecu.local'.

Now it's done, if the ip of the ECU changes, it will (eventually) be accessible by the integration again, i'm running on docker, it's working even with reboots.
