### ISSUE TITLE
Support for ECU-3

### ISSUE THREAD

**Issue by rohrsh** [ksheumaker/homeassistant-apsystems_ecur#156]
Hi there

I have an old ECU-3 device, installed by "ZEN Energy" in Australia. It looks old, maybe 2014 era. 

It is connected via ethernet, has a webpage, and sends data to the APS cloud servers. 

But I don't get any response when I try the netcat command from the readme. 

Happy to help with any diagnostics?

Cheers

![IMG_9810](https://user-images.githubusercontent.com/38928979/217415332-b02184b1-7cad-4085-a74f-cabf225109e2.jpeg)

![IMG_9811](https://user-images.githubusercontent.com/38928979/217415353-2624e427-858d-4680-97e0-b9ada981b4b5.jpeg)

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/38928979/217415423-100c6d37-83dd-41e8-a3b9-431f8b9ca1df.png">

**Comment by HAEdwin** [comment]
The ECU-3 is not compatible. I've once thought of using a proxy method to capture the data being sent to EMA. This would be great for compatibility but will require that users can do DNS-rewrites to enable traffic to EMA to pass HA. For example AdGuard and Pi-Hole can do DNS redirects. This would be a dependancy, besides that, some info will be missing like inverter temperature which is for some reason not sent to EMA.

**Comment by rohrsh** [comment]
Would you believe I am running pi-hole here .. so I'm happy to be your tester if you ever get excited about it!

I thought I could make it work [all I want is the total power generated] using the web scraper tool, but I can't wrangle the CSS. 

So I think my best shot might be the APS cloud tools.

**Comment by JSteunou** [comment]
If you have easy access to a local webpage, you can totally scrap that page to get your data. I can help you with that if needed.

**Comment by rohrsh** [comment]
It does have a local webpage. I tried to scrape that but never quite got it to work, so I would very much welcome any help. 

This is [home.txt](https://github.com/ksheumaker/homeassistant-apsystems_ecur/files/10731682/home.txt) source for the bottom frame, which has the url http://1.2.3.4/cgi-bin/home: 
<img width="773" alt="Screenshot 2023-02-14 at 9 12 19 pm" src="https://user-images.githubusercontent.com/38928979/218712903-e81d5dc1-b6bb-46d5-8339-6c829469894d.png">

I tried to get this into  Home Assistant with this scrape sensor.  

```
multiscrape:
  - resource: http://1.2.3.4/cgi-bin/home
    scan_interval: 3600
    sensor:
      - unique_id: solar_lifetime_generation
        name: Solar Total
        select: ".current-version > body > form > table > tr:nth-child(2) > td:nth-child(2)"
        value_template: '{{ ((value.split(" ")[0]) | replace ("KW", "")) }}'
        unit_of_measurement: "kWh"
```

But it generates this error: _"Updating failed with exception: illegal header line: bytearray(b'debug9')"_ This thread shows other folks reporting the same problem. https://community.home-assistant.io/t/error-scraping-apsystems-ecu-3-webpage/298242/6

Thanks for any help!
