### ISSUE TITLE
Frozen Integration with ECU-B several times a day

### ISSUE THREAD

**Issue by synack666** [ksheumaker/homeassistant-apsystems_ecur#181]
Firmware: ECU_B_1.2.26A
Version apsystems_ecur: latest

Several times a day I get no more values, frozen at the last level. in this case Cache is activated.
I have as an example this morning the ECU rebooted, short improvement, after a restart of HA it goes again for an indefinite time. Online at APSystems the data are without gaps.

**Comment by synack666** [comment]
![Screenshot 2023-04-27 133059](https://user-images.githubusercontent.com/60230729/234849480-abed0c2c-7ffa-4079-abcf-041ee6aac859.png)

**Comment by m3tc0n** [comment]
I have the same problem. I have to restart the ECU (power cycle) to get it working again.

I thought it might have something to do with the strength of the zigbee signal, but it turns out that is not the case.

**Comment by synack666** [comment]
From my point of view, the error message can be closed, since the OS 10.1 it runs without a single error, before several times a day.

**Comment by m3tc0n** [comment]
I am also using OS 10.1, but I still have the problem. So for me, this can't be closed yet.

**Comment by HAEdwin** [comment]
I can't solve this issue, what firmware versions are you running? HA doesn't need a restart, you should be fine with rebooting the ECU and switching the switch.ecu_query_device back on. Use the switch to be notified when the ECU needs a reboot or reboot the ECU automatically bij using a smart powerplug.

**Comment by m3tc0n** [comment]
Sorry for the late response. I do not know the firmware version of the ECU at the moment, but I decided to buy a smart plug and automatically reboot the ECU the moment no more data is obtained.

I have the problem every day and to restart the ECU manually is very frustrating.

**Comment by m3tc0n** [comment]
I checked the firmware. It is ECU_R_1.3.5A

**Comment by m3tc0n** [comment]
This is typical for my ECU. Any solutions?

![Screenshot_20230506-133535](https://user-images.githubusercontent.com/106514117/236621707-81b32bc0-a985-4823-a36d-4acff00060cf.png)

**Comment by HAEdwin** [comment]
Might be a hardware issue, on which hardware are you running Home Assistant? It is known that Intel NUC's might have an issue.

**Comment by m3tc0n** [comment]
Thanks for your reply. I'm running HA on a Raspberry Pi 4B, 4gb RAM, with a SSD.

**Comment by HAEdwin** [comment]
Did you have a lot of trouble configuring the ECU or did you add/remove any panels? There might also be a configuration error. I remember that I encountered issues also after adding four panels. Ended up reconfiguring the whole PV and the issue was solved.

**Comment by m3tc0n** [comment]
No, none of that. But if I read your post correctly, you recommend uninstalling and reinstalling the integration?

**Comment by HAEdwin** [comment]
No that won't change the situation. I mean resetting the ECU to factory defaults and re-add the panels.

**Comment by m3tc0n** [comment]
OK I will try that. 

For re-adding the panel, can I use the UID's of the inverters in de EMA app and put them in manually after resetting the ECU?

**Comment by wemulder** [comment]
I've been having the issue with my ECU R stopping after a few days. It looks like the automation tries to reboot the ECU, but neither the automation or even the AP Systems app/website seem to be able to connect after that happens. To get it to connect again I need to physically reboot the ECU.
For the time being, I just put in a smart switch that reboots the ECU every morning at 5am to see if that resolves the issue. I also setup an automation to send me a notification if it's using cached data (if it happens during the day despite the daily reboot).
Looks like my firmware is: ECU_R_PRO_2.1.10.

**Comment by cyberbit** [comment]
@wemulder I have the same problem as you, I use an automation to detect when cached data has been On for longer than usual, OR if the query device switch has been turned off, and run a script to reset the smart switch the ECU is using. I've been running this combo for several weeks without issue.

## Automation:
![image](https://github.com/ksheumaker/homeassistant-apsystems_ecur/assets/7350183/f7944944-ec60-49b5-8343-e000be02650d)
```yaml
alias: ECU Reset Watchdog
description: Call ECU Reset after long period ECU Using Cached Data being On
trigger:
  - platform: state
    entity_id:
      - binary_sensor.ecu_using_cached_data
    to: "on"
    for:
      hours: 0
      minutes: 16
      seconds: 0
  - platform: state
    entity_id:
      - switch.ecu_query_device
    to: "off"
    for:
      hours: 0
      minutes: 5
      seconds: 0
condition: []
action:
  - service: script.ecu_reset
    data: {}
mode: single
```

## Script:
![image](https://github.com/ksheumaker/homeassistant-apsystems_ecur/assets/7350183/e0c2f69c-51ff-4a45-86a0-b0435eac943c)

```yaml
alias: ECU Reset
sequence:
  - type: turn_off
    device_id: a3xxxxxxxxxxxx
    entity_id: switch.ecu_breaker
    domain: switch
  - delay:
      hours: 0
      minutes: 0
      seconds: 8
      milliseconds: 0
  - type: turn_on
    device_id: a3xxxxxxxxxxxx
    entity_id: switch.ecu_breaker
    domain: switch
  - delay:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - type: turn_on
    device_id: 9fxxxxxxxxxxxx
    entity_id: switch.ecu_query_device
    domain: switch
mode: single
icon: mdi:refresh
```
